### ISSUE TITLE
PHP Fatal error - running composer update

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-bootstrapper#48]
Hi,   

Although I haven't made any changes ... I always have this mistake.

``````
$ vendor/offline/oc-bootstrapper/october update
Installing new plugins
Removing private plugins
Cleared private plugins
Running artisan october:update
Reinstalling plugins:
...
Migrating all unmigrated versions
Running composer update
PHP Fatal error:  Uncaught Error: Call to a member function writeln() on null in /var/myproject/vendor/offline/oc-bootstrapper/src/Util/RunsProcess.php:57
Stack trace:
#0 /var/myproject/vendor/offline/oc-bootstrapper/src/Util/RunsProcess.php(29): OFFLINE\Bootstrapper\October\Util\Composer->checkProcessResult(2, 'Failed to run c...', '')
#1 /var/myproject/vendor/offline/oc-bootstrapper/src/Util/Composer.php(91): OFFLINE\Bootstrapper\October\Util\Composer->runProcess('"/usr/bin/php7....', 'Failed to run c...', 3600)
#2 /var/myproject/vendor/offline/oc-bootstrapper/src/Console/UpdateCommand.php(151): OFFLINE\Bootstrapper\October\Util\Composer->updateLock()
#3 /var/myproject/vendor/symfony/console/Command/Command.php(255): OFFLINE\Bootstrapper\October\Console\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/myproject/vendor/symfony/console/Application.php(992): Symfony\Component\Console\Command\C in /var/myproject/vendor/offline/oc-bootstrapper/src/Util/RunsProcess.php on line 57
``````
Any ideas ?

**Comment by damsfx** [comment]
I've got this issue with two fresh projects.  

I had to copy `composer.phar` and `composer.json` from an old (one week) project; to make it work again without any errors.

**Comment by tobias-kuendig** [comment]
I guess this line is wrong: 
https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/396d872febd55ba945ef069f3be035b6f3e7e122/src/Util/RunsProcess.php#L57

It should be:

```php
// Don't use $this->
$output->writeln('<error>' . $message . ': ' . $output . '</error>');
```

Can you check?

**Comment by damsfx** [comment]
Yeah ... It work.  

This line is just for outputing errors ??  
Although the error no longer appears, I think the error was related to one of the composer steps.

**Comment by tobias-kuendig** [comment]
The line should not be called if no error happened, so there is definitely something else wrong. Running `composer update` sometimes gives you more information.

**Comment by damsfx** [comment]
**mea culpa, mea maxima culpa**  

I was using a OctberCMS 1.1 `composer.json` file, and I think my server's Composer is out of date.
